name: SodaMachine CI/CD

on:
  push:
    branches: [ master ]        

jobs:
  build:    
    name: Build SodaMachine
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
  
  deploy:
    name: Heroku Deploy
    needs: build
    runs-on: [ubuntu-latest]
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}    
    
    steps:
      - name: Heroku login
        run: heroku login
      - name: log
        run: echo 'Heroku login successfull'
        
    
    
    
